"use client";
import {useState} from "react";
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {ArrowDownRight,ArrowUpRight,BarChart3,Bell,Building2,CalendarDays,Check,ChevronDown,CircleDollarSign,FileText,FolderKanban,LayoutDashboard,Menu,MoreHorizontal,Plus,ReceiptText,Search,Settings,Target,TrendingUp,Users,WalletCards,X} from "lucide-react";
type S="Visão geral"|"Financeiro"|"Contas"|"Propostas"|"Projetos"|"Equipe"|"Clientes"|"Valuation";
const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(v);
const chart=[{m:"Mar",r:14800,d:7600},{m:"Abr",r:18200,d:8900},{m:"Mai",r:22400,d:9800},{m:"Jun",r:19600,d:10500},{m:"Jul",r:27100,d:11800},{m:"Ago",r:32450,d:12980}];
const contas=[["New Store","Mensalidade Chatbô","05 set",1299],["Xnamai","Mensalidade Chatbô","05 set",1299],["Valente Fish","Parcela do projeto","10 set",3000],["Instituto Potala","Entrada do projeto","12 set",10000]] as const;
const projetos=[["Chatbô — New Store","New Store",78,"18 set"],["BI Mercos","Xnamai",54,"30 set"],["E-commerce Valente","Valente Fish",32,"22 out"],["Sales Game","Interno",86,"10 set"]] as const;
const propostas=[["Diagnóstico","Nova conta","Automação comercial",8500,30],["Proposta enviada","Vis Vitri","Novo site institucional",18000,50],["Negociação","Instituto Potala","Plataforma imersiva",50000,70],["Aprovada","Valente Fish","E-commerce + IA",12000,100]] as const;
const nav=[["Visão geral",LayoutDashboard],["Financeiro",BarChart3],["Contas",ReceiptText],["Propostas",FileText],["Projetos",FolderKanban],["Equipe",Users],["Clientes",Building2],["Valuation",TrendingUp]] as const;
function Metric({n,v,s,I,t=""}:{n:string,v:string,s:string,I:any,t?:string}){return <article className="metric"><i className={t}><I size={18}/></i><div><small>{n}</small><strong>{v}</strong><span>{s}</span></div></article>}
function Title({n,s}:{n:string,s:string}){return <div className="title"><div><h2>{n}</h2><p>{s}</p></div><button><CalendarDays size={16}/>Agosto de 2026<ChevronDown size={15}/></button></div>}
function Head({n,s}:{n:string,s:string}){return <header className="head"><h3>{n}</h3><p>{s}</p></header>}
function Status({children,t=""}:{children:any,t?:string}){return <span className={"status "+t}><i/>{children}</span>}
function Graph(){return <div className="graph"><ResponsiveContainer><AreaChart data={chart}><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#3ce4a3" stopOpacity=".35"/><stop offset="1" stopColor="#3ce4a3" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#233247" strokeDasharray="3 3"/><XAxis dataKey="m" stroke="#728198" axisLine={false} tickLine={false}/><YAxis stroke="#728198" axisLine={false} tickLine={false} tickFormatter={v=>v/1000+"k"}/><Tooltip contentStyle={{background:"#132134",border:"1px solid #29394e",borderRadius:10}}/><Area dataKey="r" stroke="#3ce4a3" fill="url(#g)" strokeWidth={2.5}/><Area dataKey="d" stroke="#7088a6" fill="none" strokeWidth={2}/></AreaChart></ResponsiveContainer></div>}
const metrics=<div className="metrics"><Metric n="Receita no mês" v="R$ 32.450" s="↑ 19,7% vs. julho" I={ArrowUpRight}/><Metric n="Despesas no mês" v="R$ 12.980" s="40% da receita" I={ArrowDownRight} t="amber"/><Metric n="Resultado líquido" v="R$ 19.470" s="Margem de 60%" I={CircleDollarSign} t="blue"/><Metric n="Saldo projetado" v="R$ 47.218" s="Próximos 30 dias" I={WalletCards} t="violet"/></div>;
function Overview(){return <><Title n="Boa noite, Tironi." s="Aqui está o panorama da empresa em agosto."/>{metrics}<div className="grid wide"><section className="panel"><Head n="Evolução financeira" s="Receitas e despesas nos últimos 6 meses"/><Graph/></section><section className="panel"><Head n="Pulso da empresa" s="Indicadores estratégicos"/><div className="score"><b>82</b><span>/100</span><small>Saúde excelente</small></div>{[["MRR atual","R$ 5.196",68],["Margem líquida","60%",84],["Pipeline ponderado","R$ 47.550",76]].map(x=><div className="bar" key={x[0]}><span>{x[0]}<b>{x[1]}</b></span><div><i style={{width:x[2]+"%"}}/></div></div>)}</section></div><div className="grid"><section className="panel"><Head n="Próximos recebimentos" s="Valores previstos para entrar"/>{contas.slice(0,3).map(a=><div className="item" key={a[0]}><i>{a[2].split(" ")[0]}<small>SET</small></i><span><b>{a[0]}</b><small>{a[1]}</small></span><strong>{brl(a[3])}</strong></div>)}</section><section className="panel"><Head n="Projetos ativos" s="Progresso das principais entregas"/>{projetos.slice(0,3).map(p=><div className="projectline" key={p[0]}><span><b>{p[0]}</b><small>{p[1]}</small><strong>{p[2]}%</strong></span><div><i style={{width:p[2]+"%"}}/></div></div>)}</section></div></>}
function Finance(){return <><Title n="Financeiro" s="Fluxo de caixa, resultado e projeções."/>{metrics}<section className="panel biggraph"><Head n="Fluxo de caixa realizado" s="Visão mensal de entradas e saídas"/><Graph/></section></>}
function Accounts(){return <><Title n="Contas e lançamentos" s="Controle do que entra, sai e vence ao longo do tempo."/><section className="panel"><Head n="Agenda financeira" s="Setembro de 2026"/><div className="table"><div className="row th"><span>Descrição</span><span>Vencimento</span><span>Categoria</span><span>Status</span><span>Valor</span></div>{contas.map((a,i)=><div className="row" key={a[0]}><span><b>{a[0]}</b><small>{a[1]}</small></span><span>{a[2]}</span><span>Receita</span><span><Status t={i===3?"blue":""}>{i===3?"Previsto":"A receber"}</Status></span><b className="green">+ {brl(a[3])}</b></div>)}<div className="row"><span><b>Folha de pagamento</b><small>Salários e benefícios</small></span><span>05 set</span><span>Equipe</span><span><Status t="amber">A pagar</Status></span><b className="red">− R$ 8.100</b></div></div></section></>}
function Proposals(){return <><Title n="Propostas comerciais" s="Pipeline completo, probabilidades e valores negociados."/><div className="metrics three"><Metric n="Pipeline total" v="R$ 88.500" s="4 oportunidades" I={FileText}/><Metric n="Pipeline ponderado" v="R$ 47.550" s="Por probabilidade" I={TrendingUp} t="blue"/><Metric n="Conversão" v="42%" s="Últimos 90 dias" I={Target} t="violet"/></div><div className="kanban">{["Diagnóstico","Proposta enviada","Negociação","Aprovada"].map(stage=><section key={stage}><header>{stage}<b>1</b></header>{propostas.filter(p=>p[0]===stage).map(p=><article key={p[1]}><small>{p[1]}</small><MoreHorizontal/><h3>{p[2]}</h3><strong>{brl(p[3])}</strong><footer>{p[4]}% de chance<div><i style={{width:p[4]+"%"}}/></div></footer></article>)}</section>)}</div></>}
function Projects(){return <><Title n="Projetos em andamento" s="Entregas, prazos, clientes e saúde operacional."/><div className="projectgrid">{projetos.map((p,i)=><article key={p[0]}><header><i><FolderKanban/></i><Status t={i===1?"amber":""}>{i===1?"Atenção":"No prazo"}</Status></header><small>{p[1]}</small><h3>{p[0]}</h3><span>Prazo: {p[3]}<b>{p[2]}%</b></span><div className="progress"><i style={{width:p[2]+"%"}}/></div><footer>Equipe <b>PT &nbsp; LF &nbsp; MS</b></footer></article>)}</div></>}
function Team(){let ts=[["PT","Paulo Tironi","Direção & Comercial",6500],["LF","Lucas Ferreira","Desenvolvedor Full Stack",3200],["MS","Marina Souza","Atendimento & CS",2400]];return <><Title n="Equipe e salários" s="Custos, funções e situação dos colaboradores."/><div className="metrics three"><Metric n="Custo mensal" v="R$ 12.100" s="37% da receita" I={Users}/><Metric n="Colaboradores" v="3" s="Todos ativos" I={Check} t="blue"/><Metric n="Receita por pessoa" v="R$ 10.817" s="Média no mês" I={TrendingUp} t="violet"/></div><section className="panel"><Head n="Colaboradores" s="Folha e informações principais"/><div className="table"><div className="row th"><span>Colaborador</span><span>Função</span><span>Status</span><span>Custo mensal</span><span></span></div>{ts.map(t=><div className="row" key={t[1]}><span className="person"><i>{t[0]}</i><b>{t[1]}</b></span><span>{t[2]}</span><span><Status>Ativo</Status></span><b>{brl(Number(t[3]))}</b><MoreHorizontal/></div>)}</div></section></>}
function Clients(){let cs=[["NS","New Store",1299,18706,14],["XN","Xnamai",1299,10392,8],["VF","Valente Fish",1299,15588,3],["EU","Eutec",0,3000,1]];return <><Title n="Clientes e LTV" s="Valor gerado, recorrência e tempo de relacionamento."/><div className="metrics three"><Metric n="LTV médio" v="R$ 11.922" s="Base atual" I={CircleDollarSign}/><Metric n="MRR contratado" v="R$ 5.196" s="4 contratos" I={TrendingUp} t="blue"/><Metric n="Churn" v="0%" s="Últimos 12 meses" I={Users} t="violet"/></div><div className="clients">{cs.map(c=><article key={c[1]}><i>{c[0]}</i><MoreHorizontal/><h3>{c[1]}</h3><p>Cliente há {c[4]} {c[4]===1?"mês":"meses"}</p><footer><span>MRR<b>{brl(Number(c[2]))}</b></span><span>LTV<b>{brl(Number(c[3]))}</b></span></footer></article>)}</div></>}
function Valuation(){let[m,setM]=useState(4.2),v=389400*m+124704;return <><Title n="Valuation" s="Estimativa indicativa baseada em receita, recorrência e múltiplo."/><section className="value"><div><span>Valuation estimado</span><strong>{brl(v)}</strong><p>Faixa sugerida: {brl(v*.8)} — {brl(v*1.2)}</p></div><TrendingUp/></section><div className="grid"><section className="panel"><Head n="Premissas do cálculo" s="Ajuste o múltiplo para simular cenários"/><p className="assume">Receita anualizada <b>R$ 389.400</b></p><p className="assume">Receita recorrente anual <b>R$ 62.352</b></p><div className="slider">Múltiplo da receita <b>{m.toFixed(1)}x</b><input type="range" min="1" max="8" step=".1" value={m} onChange={e=>setM(+e.target.value)}/></div></section><section className="panel"><Head n="Direcionadores de valor" s="O que mais impacta a estimativa"/>{[["Receita recorrente","MRR previsível melhora o múltiplo."],["Margem elevada","60% de resultado líquido no mês."],["Concentração de clientes","Diversificar reduz o risco."]].map(x=><div className="driver" key={x[0]}><ArrowUpRight/><span><b>{x[0]}</b><small>{x[1]}</small></span></div>)}</section></div><p className="note">Estimativa gerencial. Uma avaliação formal exige análise contábil, jurídica e de mercado.</p></>}
export default function Home(){let[s,setS]=useState<S>("Visão geral"),[menu,setMenu]=useState(false),[modal,setModal]=useState(false),[saved,setSaved]=useState(false);let view:Record<S,any>={"Visão geral":<Overview/>,Financeiro:<Finance/>,Contas:<Accounts/>,Propostas:<Proposals/>,Projetos:<Projects/>,Equipe:<Team/>,Clientes:<Clients/>,Valuation:<Valuation/>};function save(){setSaved(true);setTimeout(()=>{setSaved(false);setModal(false)},800)}return <div className="app"><aside className={menu?"open":""}><div className="brand"><i>T</i><span><b>TIRONI</b><small>TECH CONTROL</small></span><button onClick={()=>setMenu(false)}><X/></button></div><nav>{nav.map(([n,I])=><button className={s===n?"active":""} onClick={()=>{setS(n);setMenu(false)}} key={n}><I/>{n}{n==="Contas"&&<b>5</b>}</button>)}</nav><div className="bottom"><button><Settings/>Configurações</button><div><i>PT</i><span><b>Paulo Tironi</b><small>Administrador</small></span></div></div></aside>{menu&&<button className="overlay" onClick={()=>setMenu(false)}/>}<main><header className="top"><button className="menub" onClick={()=>setMenu(true)}><Menu/></button><div><small>GESTÃO EMPRESARIAL</small><h1>{s}</h1></div><label><Search/><input placeholder="Buscar no sistema..."/></label><button className="bell"><Bell/></button><button className="primary" onClick={()=>setModal(true)}><Plus/>Novo lançamento</button></header><div className="content">{view[s]}</div></main>{modal&&<div className="backdrop" onMouseDown={()=>setModal(false)}><section className="modal" onMouseDown={e=>e.stopPropagation()}><header><div><h2>Novo lançamento</h2><p>Registre uma entrada ou saída financeira.</p></div><button onClick={()=>setModal(false)}><X/></button></header><div className="toggle"><button className="active"><ArrowUpRight/>Entrada</button><button><ArrowDownRight/>Saída</button></div><label>Descrição<input placeholder="Ex.: Mensalidade Chatbô"/></label><div className="formgrid"><label>Valor<input placeholder="R$ 0,00"/></label><label>Vencimento<input type="date" defaultValue="2026-09-05"/></label></div><label>Categoria<select><option>Receita recorrente</option><option>Projeto</option><option>Equipe</option></select></label><footer><button onClick={()=>setModal(false)}>Cancelar</button><button className="primary" onClick={save}>{saved?<><Check/>Salvo!</>:"Salvar lançamento"}</button></footer></section></div>}</div>}
